import os
from fpdf import FPDF
from datetime import datetime
from typing import Any, Dict


def _safe(val, default=""):
    """Ensure no None values reach FPDF's text methods."""
    if val is None:
        return default
    return str(val)


class PDFResumeGenerator(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by T.R.E.X AI on {datetime.now().strftime('%Y-%m-%d')} - Page {self.page_no()}", 0, 0, "C")


def generate_resume_pdf(data: Dict[str, Any], output_path: str) -> str:
    pdf = PDFResumeGenerator()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header - Personal Info
    personal = data.get("personal_info", {})
    if personal is None:
        personal = {}

    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(31, 41, 55)  # dark gray
    pdf.cell(0, 15, _safe(personal.get("name"), "YOUR NAME").upper(), ln=True, align="C")

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(75, 85, 99)  # gray
    contact_info = []
    if personal.get("email"): contact_info.append(_safe(personal["email"]))
    if personal.get("phone"): contact_info.append(_safe(personal["phone"]))
    if personal.get("location"): contact_info.append(_safe(personal["location"]))
    pdf.cell(0, 5, "  |  ".join(contact_info), ln=True, align="C")

    pdf.ln(10)
    pdf.set_draw_color(209, 213, 219)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Summary
    summary = data.get("summary")
    if summary:
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 8, "PROFESSIONAL SUMMARY", ln=True)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 5, _safe(summary))
        pdf.ln(5)

    # Experience
    experience = data.get("experience")
    if experience:
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 8, "EXPERIENCE", ln=True)
        for exp in experience:
            if exp is None:
                continue
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(31, 41, 55)
            # Role and Dates
            pdf.cell(100, 6, _safe(exp.get("role"), "Role"))
            pdf.set_x(150)
            pdf.set_font("helvetica", "B", 9)
            dates = f"{_safe(exp.get('start_date'))} - {_safe(exp.get('end_date'), 'Present')}"
            pdf.cell(50, 6, dates, ln=True, align="R")

            # Company and Location
            pdf.set_font("helvetica", "I", 10)
            pdf.set_text_color(75, 85, 99)
            pdf.cell(100, 5, _safe(exp.get("company"), "Company"))
            pdf.set_x(150)
            pdf.cell(50, 5, _safe(exp.get("location")), ln=True, align="R")

            # Bullets
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(55, 65, 81)
            for bullet in (exp.get("bullets") or []):
                if bullet is None:
                    continue
                pdf.set_x(15)
                pdf.cell(5, 5, "-")
                pdf.multi_cell(0, 5, _safe(bullet))
            pdf.ln(3)

    # Projects
    projects = data.get("projects")
    if projects:
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 8, "PROJECTS", ln=True)
        for proj in projects:
            if proj is None:
                continue
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(31, 41, 55)
            pdf.cell(0, 6, _safe(proj.get("name"), "Project Name"), ln=True)

            tech_stack = proj.get("tech_stack")
            if tech_stack:
                pdf.set_font("helvetica", "I", 9)
                pdf.set_text_color(107, 114, 128)
                # Filter out None values from tech_stack
                stack_items = [_safe(t) for t in tech_stack if t is not None]
                pdf.cell(0, 5, "Tech Stack: " + ", ".join(stack_items), ln=True)

            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(55, 65, 81)
            pdf.multi_cell(0, 5, _safe(proj.get("description")))
            pdf.ln(3)

    # Education
    education = data.get("education")
    if education:
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 8, "EDUCATION", ln=True)
        for edu in education:
            if edu is None:
                continue
            pdf.set_font("helvetica", "B", 10)
            degree_text = _safe(edu.get("degree"), "Degree")
            if edu.get("field"):
                degree_text += f" in {_safe(edu['field'])}"
            pdf.cell(100, 6, degree_text)
            pdf.set_x(150)
            dates = f"{_safe(edu.get('start_date'))} - {_safe(edu.get('end_date'))}"
            pdf.cell(50, 6, dates, ln=True, align="R")

            pdf.set_font("helvetica", "I", 10)
            pdf.set_text_color(75, 85, 99)
            pdf.cell(100, 5, _safe(edu.get("institution"), "Institution"))
            pdf.set_x(150)
            pdf.cell(50, 5, _safe(edu.get("location")), ln=True, align="R")
            pdf.ln(2)

    # Skills
    skills = data.get("skills")
    if skills:
        pdf.ln(5)
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 8, "TECHNICAL SKILLS", ln=True)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)

        if isinstance(skills, dict):
            for category, items in skills.items():
                if items is None:
                    continue
                pdf.set_font("helvetica", "B", 10)
                pdf.write(5, f"{_safe(category)}: ")
                pdf.set_font("helvetica", "", 10)
                # Filter None items
                safe_items = [_safe(i) for i in items if i is not None]
                pdf.write(5, ", ".join(safe_items) + "\n")
        elif isinstance(skills, list):
            safe_items = [_safe(i) for i in skills if i is not None]
            pdf.write(5, ", ".join(safe_items))
        pdf.ln(5)

    # Ensure storage directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    print(f"[PDF] Successfully generated: {output_path}")
    return output_path
